<?php

include_once('debut_event.features.inc');

/**
 * Implements hook_menu_alter().
 *
 * Add a local action link to the event view page.
 */
function debut_event_menu_alter(&$items) {
  if (isset($items['node/add/event'])) {
    $items['event/add'] = $items['node/add/event'];
    $items['event/add']['title'] = 'Add a new event';
    $items['event/add']['type'] = MENU_LOCAL_ACTION;
  }
}

/**
 * Implements hook_admin_paths().
 *
 * Declare event/add as an admin path to trigger e.g. admin theme and overlay.
 */
function debut_event_admin_paths() {
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'event/add' => TRUE,
    );
    return $paths;
  }
}

/**
 * Implements hook_features_export_alter().
 *
 * Remove the tags vocabulary, which we create at install time so as not to
 * create a dependency on a feature providing the vocabulary.
 */
function debut_event_features_export_alter(&$export, $module_name) {
  if ($module_name == 'debut_event' && isset($export['features']['taxonomy']) && isset($export['features']['taxonomy']['tags'])) {
    unset($export['features']['taxonomy']['tags']);
  }
}

/**
 * Implements hook_date_format_types().
 */
function debut_event_date_format_types() {
  return array(
    'event_day' => t('Day'),
    'event_time' => t('Time'),
  );
}

/**
 * Implements hook_date_formats().
 */
function debut_event_date_formats() {
  $condensed = array(
    'event_day' => array(
      'l, M j',
      'l, j M',
    ),
    'event_time' => array(
      'g:ia',
      'H:i',
    ),
  );
  $formats = array();
  foreach ($condensed as $type => $f) {
    foreach ($f as $format) {
      $formats[] = array(
        'type' => $type,
        'format' => $format,
        'locales' => array(),
      );
    }
  }
  return $formats;
}

/**
 * Implements hook_field_default_fields_alter().
 *
 * If debut_media module is present, use an image style it provides instead of
 * the default 'large' style.
 */
function debut_event_field_default_fields_alter(&$fields) {
  if (isset($fields['node-event-field_content_image']) && module_exists('debut_media') && !debut_event_is_recreating('debut_event')) {
    $fields['node-event-field_content_image']['field_instance']['display']['default']['settings']['image_style'] = 'medium_large';
  }
}

/**
 * Determine whether a feature is being recreated.
 */
function debut_event_is_recreating($feature = NULL) {
  // Test for Drush usage.
  if (function_exists('drush_get_command') && $command = drush_get_command()) {
    switch($command['command']) {
      case 'features-update-all':
        return TRUE;
      case 'features-update':
        // If a specific feature was requested, test for it. If not, return
        // true for any feature recreation.
        return is_null($feature) || in_array($feature, $command['arguments']);
    }
  }

  // Test for admin UI usage.
  $feature = is_null($feature) ? arg(3) : $feature;
  if ($_GET['q'] == "admin/structure/features/{$feature}/recreate") {
    return TRUE;
  }
  return FALSE;
}

