<?php
// $Id: logintoboggan_rules.module,v 1.3 2011/01/06 07:04:44 thehunmonkgroup Exp $


/**
 * @file
 * Logintoboggan Rules module
 *
 * This module provides integration of LoginToboggan module with Rules module
 */



/**
 * Implement hook_user()
 *
 */
function logintoboggan_rules_user_update(&$edit, $account) {
  if (!empty($account->logintoboggan_email_validated)) {
    rules_invoke_event('logintoboggan_validated', $account);
  }
}

