; $Id: debut_social.make.inc,v 1.6 2011/02/11 00:48:17 nedjo Exp $

; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[advanced_help][subdir] = contrib
projects[advanced_help][version] = 1.0-beta1
projects[captcha][subdir] = contrib
projects[captcha][version] = 1.0-alpha2
projects[captcha][patch][] = http://drupal.org/files/issues/825088-19-captcha_ctools_export.patch
projects[context][subdir] = contrib
projects[context][version] = 3.0-alpha3
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.0-alpha2
projects[debut][subdir] = contrib
projects[debut][version] = 1.x-beta1
projects[debut_social][subdir] = contrib
projects[debut_social][version] = 1.x-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.x-dev 
projects[follow][subdir] = contrib
projects[follow][version] = 1.x-dev
projects[forward][subdir] = contrib
projects[forward][version] = 1.0-alpha3
projects[service_links][subdir] = contrib
projects[service_links][version] = 2.x-dev
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0-beta2
