<?php
/**
 * @file
 * Code for the Open Outreach core feature.
 */

include_once 'openoutreach_core.features.inc';

/**
 * Implements hook_context_default_contexts_alter().
 *
 * If the debut_blogger module is enabled, display the shortcut block to users
 * with the blogger role.
 */
function openoutreach_core_context_default_contexts_alter(&$contexts) {
  if (isset($contexts['shortcut']) && module_exists('debut_blog') && !apps_compatible_feature_is_recreating('openoutreach_core')) {
    $contexts['shortcut']->conditions['user']['values']['blogger'] = 'blogger';
  }
}
