<?php

/**
 * @file
 * Provide the bookmarking support for various browser.
 */
function favorite_services_service_links() {
  $links['favorite'] = array(
    'name' => t('Favorite'),
    'description' => t('Add this page in your favorites'),
    'link' => url('', array('absolute' => TRUE, 'query' => array('q' => '<encoded-url>#<encoded-title>'))),
    'attributes' => array('style' => 'display:none;'),
    'javascript' => 'favorite_services.js',
  );

  return $links;
}
