<?php

/**
 * @file
 * Widgets show some info about the content and the social network.
 */

/**
 * Implements hook_service_links().
 */
function widget_services_service_links() {
  $links = array();

  $links['facebook_widget'] = array(
    'name' => 'Share on Facebook',
    'link' => 'http://www.facebook.com/sharer.php',
    'description' => t('Share on Facebook'),
    'javascript' => array(
      'http://static.ak.fbcdn.net/connect.php/js/FB.Share',
      'facebook_share.js',
    ),
    'icon' => 'facebook.png',
    'style' => SERVICE_LINKS_STYLE_TEXT,
    'callback' => 'ws_facebook_widget_share',
  );
  $links['twitter_widget'] = array(
    'name' => 'Tweet Widget',
    'link' => 'http://twitter.com/share?url=<encoded-short-url>&count=<data-count>&via=<data-via>&text=<encoded-title>&counturl=<encoded-url>',
    'icon' => 'twitter.png',
    'description' => t('Tweet This'),
    'attributes' => array('class' => array('twitter-share-button')),
    'javascript' => 'http://platform.twitter.com/widgets.js',
    'style' => SERVICE_LINKS_STYLE_EMPTY,
    'callback' => 'ws_twitter_widget_data',
  );
  $links['facebook_like'] = array(
    'name' => 'Facebook Like',
    'link' => 'http://www.facebook.com/plugins/like.php?href=<encoded-url>&layout=<layout>&show_faces=<show_faces>&action=<action>&colorscheme=<colorscheme>&width=<width>&height=<height>&font=<font>',
    'icon' => 'facebook.png',
    'description' => t('I Like it'),
    'javascript' => 'facebook_like.js',
    'style' => SERVICE_LINKS_STYLE_EMPTY,
    'callback' => 'ws_facebook_widget_like',
  );

  return $links;
}

/**
 * Callback function for Twitter Widget.
 */
function ws_twitter_widget_data(&$service, $subst) {
  static $subst;

  if (!isset($subst)) {
    $subst = array(
      'count' => variable_get('service_links_tw_data_count', 'horizontal'),
      'via' => urlencode(variable_get('service_links_tw_data_via' , '')),
    );
  }
  
  $service['url'][1] = array_merge($service['url'][1], $subst);
}

/**
 * Callback function for Facebook Share Widget.
 */
function ws_facebook_widget_share(&$service, $subst) {
  static $fs_settings;

  if (!isset($fs_settings)) {
    $fs_settings = array(
      'type' => variable_get('service_links_fs_type', 'button_count'),
    );

    drupal_add_js(array('ws_fs' => $fs_settings), 'setting');
  }

  $service['attributes']['rel'] = $subst['url'];
}

/**
 * Callback function for Facebook Like Widget.
 */
function ws_facebook_widget_like(&$service, $subst) {
  static $subst;

  if (!isset($subst)) {
    $subst = array(
      'layout' => variable_get('service_links_fl_layout', 'button_count'),
      'show_faces' => variable_get('service_links_fl_show_faces', 'false'),
      'action' => variable_get('service_links_fl_action', 'like'),
      'colorscheme' => variable_get('service_links_fl_colorscheme', 'light'),
      'font' => variable_get('service_links_fl_font', ''),
      'width' => variable_get('service_links_fl_width', '100'),
      'height' => '21',
    );

    $fl_settings = array(
      'width' => $subst['width'],
      'height' => '21',
    );

    switch ($subst['layout']) {
      case 'standard':
        $fl_settings['height'] = '80';
        $subst['height'] = '80';
        break;
      case 'box_count':
        $fl_settings['height'] = '65';
        $subst['height'] = '65';
        break;
      //case 'button_count':
        //$fl_settings['height'] = 21;
        //$subst['height'] = '21';
        //break;
    }

    drupal_add_js(array('ws_fl' => $fl_settings), 'setting');
  }

  $service['url'][1] = array_merge($service['url'][1], $subst);
}

/**
 * Implements hook_menu().
 */
function widget_services_menu() {
  $items = array();

  $items['admin/config/services/service-links/widgets'] = array(
    'title' => 'Widgets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('widget_services_admin'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    //'parent' => 'admin/config/services/service-links',
    'file' => 'widget_services.admin.inc',
  );

  return $items;
}
