; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.x-dev
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta3
projects[debut_seo][subdir] = contrib
projects[debut_seo][version] = 1.0-beta2
projects[features][subdir] = contrib
projects[features][version] = 1.0-beta5
projects[globalredirect][subdir] = contrib
projects[globalredirect][version] = 1.4
projects[metatag][subdir] = contrib
projects[metatag][version] = 1.0-alpha4
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.0
projects[token][subdir] = contrib
projects[token][version] = 1.0-beta7
projects[xmlsitemap][subdir] = contrib
projects[xmlsitemap][version] = 2.0-rc1

