; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.x-dev
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta3
projects[debut_seo][subdir] = contrib
projects[debut_seo][version] = 1.0-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.0-beta4
projects[globalredirect][subdir] = contrib
projects[globalredirect][version] = 1.3
projects[metatag][subdir] = contrib
projects[metatag][version] = 1.0-alpha3
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.0-rc2
projects[token][subdir] = contrib
projects[token][version] = 1.0-beta6
projects[xmlsitemap][subdir] = contrib
projects[xmlsitemap][version] = 2.0-beta3

