; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[advanced_help][subdir] = contrib
projects[advanced_help][version] = 1.0
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta3
projects[debut_wysiwyg][subdir] = contrib
projects[debut_wysiwyg][version] = 1.0-beta4
projects[entity][subdir] = contrib
projects[entity][version] = 1.0-rc1
projects[features][subdir] = contrib
projects[features][version] = 1.0-beta4
projects[file_entity][subdir] = contrib
projects[file_entity][version] = 2.x-dev
projects[libraries][subdir] = contrib
projects[libraries][version] = 1.0
projects[media][subdir] = contrib
projects[media][version] = 2.0-unstable2
projects[media][patch][http://drupal.org/files/media-install-error-1311828-28.patch] = http://drupal.org/files/media-install-error-1311828-28.patch
projects[styles][subdir] = contrib
projects[styles][version] = 2.0-alpha8
projects[wysiwyg][subdir] = contrib
; Use dev release until the features integration is released with 2.2.
projects[wysiwyg][version] = 2.x-dev
; Ckeditor
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.2/ckeditor_3.6.2.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"

