
; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[captcha][subdir] = contrib
projects[captcha][version] = 1.0-alpha2
projects[captcha][patch][http://drupal.org/files/issues/825088-19-captcha_ctools_export.patch] = http://drupal.org/files/issues/825088-19-captcha_ctools_export.patch
projects[comment_notify][subdir] = contrib
projects[comment_notify][version] = 1.0-rc1
projects[context][subdir] = contrib
projects[context][version] = 3.0-beta2
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.x-dev
projects[debut][subdir] = contrib
projects[debut][version] = 1.0-beta3
projects[debut_comment][subdir] = contrib
projects[debut_comment][version] = 1.0-beta4
projects[features][subdir] = contrib
projects[features][version] = 1.0-beta4
projects[logintoboggan][subdir] = contrib
projects[logintoboggan][version] = 1.2
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0-beta4
