<?php

include_once('debut_blog.features.inc');

/**
 * Implements hook_init().
 */
function debut_blog_init() {
  drupal_add_css(drupal_get_path('module', 'debut_blog') . '/debut_blog.css');
}

/**
 * Implements hook_menu_alter().
 *
 * Add a local action link to the blog view page.
 */
function debut_blog_menu_alter(&$items) {
  if (isset($items['node/add/blog'])) {
    $items['blog/add'] = $items['node/add/blog'];
    $items['blog/add']['title'] = 'Add a new blog post';
    $items['blog/add']['type'] = MENU_LOCAL_ACTION;
  }
}

/**
 * Implements hook_admin_paths().
 *
 * Declare blog/add as an admin path to trigger e.g. admin theme and overlay.
 */
function debut_blog_admin_paths() {
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'blog/add' => TRUE,
    );
    return $paths;
  }
}

