; $Id: debut_media.make.inc,v 1.4 2011/02/11 00:47:32 nedjo Exp $

; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[context][subdir] = contrib
projects[context][version] = 3.0-alpha3
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.0-alpha2
projects[debut][subdir] = contrib
projects[debut][version] = 1.x-beta1
projects[debut_media][subdir] = contrib
projects[debut_media][version] = 1.x-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.x-dev 
projects[media][subdir] = contrib
projects[media][version] = 1.0-beta3
projects[media_browser_plus][subdir] = contrib
projects[media_browser_plus][version] = 1.0-beta2
projects[media_gallery][subdir] = contrib
projects[media_gallery][version] = 1.0-beta3
projects[media_youtube][subdir] = contrib
projects[media_youtube][version] = 1.0-alpha4
projects[styles][subdir] = contrib
projects[styles][version] = 2.0-alpha5
projects[views][subdir] = contrib
projects[views][version] = 3.0-alpha1
