<?php

include_once('debut_media.features.inc');

/**
 * Implements hook_menu_alter().
 *
 * Convert the 'file/add' item to a local action.
 */
function debut_media_menu_alter(&$items) {
  if (isset($items['file/add'])) {
    $items['file/add']['type'] = MENU_LOCAL_ACTION;
  }
}

/**
 * Implements hook_menu_link_alter().
 *
 * Set the file/% link to hidden to avoid navigation menu error,
 * see http://drupal.org/node/1018614.
 *
 * @todo: remove when http://drupal.org/node/1018614 is fixed.
 */
function debut_media_menu_link_alter(&$item) {
  if ($item['link_path'] == 'file/%') {
    $item['hidden'] = TRUE;
  }
}

/**
 * Implements hook_entity_info_alter().
 *
 * Enable custom settings for the 'full' file view mode.
 * See http://drupal.org/node/1291428.
 */
function debut_media_entity_info_alter(&$entity_info) {
  if (isset($entity_info['file']['view modes']['full'])) {
    $entity_info['file']['view modes']['full']['custom settings'] = TRUE;
  }
}

/**
 * Implements hook_image_styles_alter().
 *
 * Restore previous dimensions of media_thumbnail (was small_thumbnail).
 */
function debut_media_image_styles_alter(&$styles) {
  // Check that we only affect a default style.
  if (isset($styles['media_thumbnail']['storage']) && $styles['media_thumbnail']['storage'] == IMAGE_STORAGE_DEFAULT) {
    $styles['media_thumbnail']['label'] = t('Media thumbnail (180x180)');
    foreach($styles['media_thumbnail']['effects'] as $key => $effect) {
      if ($effect['name'] == 'image_scale_and_crop') {
        $styles['media_thumbnail']['effects'][$key]['data'] = array('width' => 180, 'height' => 180);
      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function debut_media_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_info_alter') {
    // Move debut_media_entity_info_alter() to the end of the list.
    // module_implements() iterates through $implementations with a foreach
    // loop which PHP iterates in the order that the items were added, so to
    // move an item to the end of the array, we remove it and then add it.
    $group = $implementations['debut_media'];
    unset($implementations['debut_media']);
    $implementations['debut_media'] = $group;
  }
}

/**
 * Implements hook_jcarousel_options_alter(().
 *
 * Swap in setup and reload callbacks to make the media carousel responsive.
 */
function debut_media_jcarousel_options_alter(&$options, $class_name) {
  static $added = FALSE;

  if (!empty($options['view_options']['view_name']) && $options['view_options']['view_name'] == 'media') {
    foreach (array('setupCallback', 'reloadCallback') as $callback) {
      if (!isset($options[$callback])) {
        $options[$callback] = 'Drupal.debutMedia.' . $callback;
        if (!$added) {
          drupal_add_css(drupal_get_path('module', 'debut_media') . '/debut_media.css', array('weight' => 10));
          drupal_add_js(drupal_get_path('module', 'debut_media') . '/debut_media.js');
          $added = TRUE;
        }
      }
    }
  }
}

/**
 * Implementation of Styles module hook_styles_default_styles().
 */
function debut_media_styles_default_styles() {
  return array(
    'file' => array(
      'styles' => array(
        'medium_large' => array(
          'label' => t('Medium large'),
          'description' => t('A medium large format of the media.'),
        ),
        'small_square_thumbnail' => array(
          'label' => t('Small square thumbnail'),
          'description' => t('A small, square format of the media.'),
        ),
      ),
    ),
  );
}

/**
 * Implementation of Styles module hook_styles_default_presets_alter().
 */
function debut_media_styles_default_presets_alter(&$presets) {
  foreach (array_keys(debut_media_image_default_styles()) as $image_style) {
    // Cover the containers defined by file_styles and media_youtube.
    foreach (array('application', 'image', 'audio', 'video', 'default', 'media_youtube', 'media_vimeo') as $type) {
      // Ensure another module hasn't removed the container.
      if (isset($presets['file']['containers'][$type])) {
        $presets['file']['containers'][$type]['styles'][$image_style] = array(
          'default preset' => 'medium_large',
        );
        $presets['file']['containers'][$type]['presets'][$image_style] = array(
          array(
            'name' => 'image_style',
            'settings' => array(
              'image_style' => $image_style,
            ),
          ),
          array(
            'name' => 'thumbnail',
            'settings' => array(),
          ),
        );
      }
    }
  }
}

/**
 * Implementation of hook_field_default_fields_alter().
 *
 * Selectively add media fields to content types provided by features. To
 * receive a media_field instance, the feature should include the following in
 * its .info file:
 * debut[media][node_types][my_content_type] = my_content_type
 * where my_content_type is the name of a feature-provided content type.
 *
 * The media field status of a feature's content type can be altered by using
 * hook_system_info_alter(). Example:
 * %code
 * function example_system_info_alter(&$info, $module, $type) {
 *   if ($type == $module && $module->name == 'debut_article') {
 *     unset($info['debut']['media']['article']);
 *   }
 * }
 * %endcode
 */
function debut_media_field_default_fields_alter(&$items) {
  // Only add fields if we're altering data provided by the media module.
  // 'file-application-field_tags' is provided by debut_media.
  if (isset($items['file-application-field_tags'])) {
    $node_types = debut_media_get_media_types();
    // Add media fields to the designated node types.
    if (!empty($node_types)) {
      $field = debut_media_media_field();
      foreach (array_keys($node_types) as $type) {
        // Don't override an existing field. This allows features to provide
        // their own version of the field.
        if (!isset($items["node-$type-field_media"])) {
          $field['field_instance']['bundle'] = $type;
          $items["node-$type-field_media"] = $field;
        }
      }
    }
  }
}

/**
 * Implements hook_features_export_alter().
 *
 * Remove field_media instances.
 * Remove incorrect dependencies on debut_media, which are assigned to modules
 * that provide content types we've added the field_media field to.
 */
function debut_media_features_export_alter(&$export, $module_name) {
  $node_types = debut_media_get_media_types();

  if ($module_name == 'debut_media') {
    // Remove any media fields from export.
    if (isset($export['features']['field'])) {
      foreach (array_keys($node_types) as $type) {
        unset($export['features']['field']["node-$type-field_media"]);
      }
    }
  }
  // Remove incorrect dependencies.
  elseif ($node_types && in_array($module_name, $node_types)) {
    $key = array_search('debut_media', $export['dependencies']);
    unset($export['dependencies'][$key]);
  }
}

/**
 * Implements hook_system_info_alter().
 *
 * Claim the fields that debut_media provides.
 */
function debut_media_system_info_alter(&$info, $file, $type) {
  static $processing;
  $node_types = NULL;

  if ($type == 'module'  && $file->name == 'debut_media') {
    if (!$processing) {
      // Set a flag to prevent recursion.
      $processing = TRUE;
      $node_types = debut_media_get_media_types();
      $processing = FALSE;
    }

    if ($node_types) {
      foreach (array_keys($node_types) as $type) {
        $info['features']['field'][] = "node-$type-field_media";
      }
    }
  }
}

/**
 * Return the feature-provided node types that take a media field and the
 * feature that provides them.
 */
function debut_media_get_media_types() {
  // Get features modules and determine which if claim media.
  $features = features_get_features();
  $node_types = array();
  foreach ($features as $feature) {
    $info = $feature->info;
    if (isset($info['debut']) && isset($info['debut']['media']) && isset($info['debut']['media']['node_types'])) {
      $node_types = array_merge($node_types, array_fill_keys($info['debut']['media']['node_types'], $feature->name));
    }
  }
  return $node_types;
}

/**
 * Return the structure of the media field.
 *
 * The instance bundle is marked as 'placeholder'. It should be converted to
 * the appropriate node type before being used.
 */
function debut_media_media_field() {
  $field = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_media',
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'module' => 'file',
      'settings' => array(
        'display_default' => 0,
        'display_field' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'file',
    ),
    'field_instance' => array(
      'bundle' => 'placeholder',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'file_entity',
          'settings' => array(
            'file_view_mode' => 'media_large',
          ),
          'type' => 'file_rendered',
          'weight' => '4',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_media',
      'label' => 'Media',
      'required' => 0,
      'settings' => array(
        'description_field' => 0,
        'file_directory' => '',
        'file_extensions' => 'jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp',
        'max_filesize' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'media',
        'settings' => array(
          'allowed_schemes' => array(
            'public' => 'public',
            'vimeo' => 'vimeo',
            'youtube' => 'youtube',
          ),
          'allowed_types' => array(
            'audio' => 0,
            'default' => 'default',
            'image' => 'image',
            'video' => 'video',
          ),
          'browser_plugins' => array(
            'library' => 0,
            'media_default--media_browser_1' => 0,
            'media_internet' => 0,
            'upload' => 0,
          ),
          'progress_indicator' => 'throbber',
        ),
        'type' => 'media_generic',
        'weight' => '10',
      ),
    ),
  );

  return $field;
}

/**
 * Implements hook_file_default_displays_alter().
 *
 * Clone settings for 'media_large' to new 'full' view mode and fix weighting
 * of video preview images.
 *
 * @todo: remove 'media_large' to 'full' cloning once media provider modules
 * catch up. See http://drupal.org/node/1291428.
 */
function debut_media_file_default_displays_alter(&$items) {
  // Clone settings for 'media_large' to new 'full' view mode.
  $info = entity_get_info('file');
  $bundles = array_keys($info['bundles']);
  $view_modes = array_keys($info['view modes']);

  foreach ($items as $key => $data) {
    list($file_type, $view_mode, $formatter_name) = explode('__', $key);
    if ($view_mode == 'media_large') {
      $display_name = implode('__', array($file_type, 'full', $formatter_name));
      if (!isset($items[$display_name])) {
        $items[$display_name] = clone($data);
        $items[$display_name]->name = $display_name;
      }
    }
  }
  // Fix weighting of video preview images.
  foreach (array('video__preview__media_vimeo_image', 'video__preview__media_youtube_image') as $key) {
    if (isset($items[$key])) {
      $items[$key]->weight = -10;
    }
  }
}
