; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[apps_compatible][subdir] = contrib
projects[apps_compatible][version] = 1.0-alpha3
projects[context][subdir] = contrib
projects[context][version] = 3.0-beta4
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.2
projects[debut_media][subdir] = contrib
projects[debut_media][version] = 1.0-rc3
projects[features][subdir] = contrib
projects[features][version] = 1.0
projects[file_admin][subdir] = contrib
projects[file_admin][version] = 1.0-beta2
projects[file_entity][subdir] = contrib
projects[file_entity][version] = 2.0-unstable7
projects[jcarousel][subdir] = contrib
projects[jcarousel][version] = 2.6
projects[media][subdir] = contrib
projects[media][version] = 2.0-unstable7
projects[media_browser_plus][subdir] = contrib
projects[media_browser_plus][version] = 1.0-beta3
projects[media_vimeo][subdir] = contrib
projects[media_vimeo][version] = 1.0-beta5
projects[media_youtube][subdir] = contrib
projects[media_youtube][version] = 1.0-beta3
projects[multiform][subdir] = contrib
projects[multiform][version] = 1.0
projects[remote_stream_wrapper][subdir] = contrib
projects[remote_stream_wrapper][version] = 1.0-beta4
projects[transliteration][subdir] = contrib
projects[transliteration][version] = 3.1
projects[views][subdir] = contrib
projects[views][version] = 3.5

; Libraries
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/zipball/v1.3.16"
libraries[colorbox][directory_name] = "colorbox"

