; $Id: debut_article.make.inc,v 1.8 2011/02/11 00:46:03 nedjo Exp $

; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[advanced_help][subdir] = contrib
projects[advanced_help][version] = 1.0-beta1
projects[captcha][subdir] = contrib
projects[captcha][version] = 1.0-alpha2
projects[captcha][patch][] = http://drupal.org/files/issues/825088-19-captcha_ctools_export.patch
projects[context][subdir] = contrib
projects[context][version] = 3.0-alpha3
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.0-alpha2
projects[debut][subdir] = contrib
projects[debut][version] = 1.x-beta1
projects[debut_article][subdir] = contrib
projects[debut_article][version] = 1.x-beta1
projects[debut_media][subdir] = contrib
projects[debut_media][version] = 1.x-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.x-dev 
projects[media][subdir] = contrib
projects[media][version] = 1.0-beta3
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.0-beta1
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0-beta2
projects[styles][subdir] = contrib
projects[styles][version] = 2.0-alpha5
projects[token][subdir] = contrib
projects[token][version] = 1.0-beta1
projects[views][subdir] = contrib
projects[views][version] = 3.0-alpha1
