<?php

include_once('debut_article.features.inc');

/**
 * Implements hook_init().
 */
function debut_article_init() {
  drupal_add_css(drupal_get_path('module', 'debut_article') . '/debut_article.css');
}

/**
 * Implements hook_menu_alter().
 *
 * Add a local action link to the article view page.
 */
function debut_article_menu_alter(&$items) {
  if (isset($items['node/add/article'])) {
    $items['article/add'] = $items['node/add/article'];
    $items['article/add']['title'] = 'Add a new article';
    $items['article/add']['type'] = MENU_LOCAL_ACTION;
  }
}

/**
 * Implements hook_admin_paths().
 *
 * Declare article/add as an admin path to trigger e.g. admin theme and overlay.
 */
function debut_article_admin_paths() {
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'article/add' => TRUE,
    );
    return $paths;
  }
}

/**
 * Implements hook_features_export_alter().
 *
 * Remove the tags vocabulary, which we create at install time so as not to
 * create a dependency on a feature providing the vocabulary.
 */
function debut_article_features_export_alter(&$export, $module_name) {
  if ($module_name == 'debut_article' && isset($export['features']['taxonomy']) && isset($export['features']['taxonomy']['tags'])) {
    unset($export['features']['taxonomy']['tags']);
  }
}
