; $Id: debut_section.make.inc,v 1.5 2011/02/11 00:47:51 nedjo Exp $

; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[context][subdir] = contrib
projects[context][version] = 3.0-alpha3
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.0-alpha2
projects[debut][subdir] = contrib
projects[debut][version] = 1.x-beta1
projects[debut_media][subdir] = contrib
projects[debut_media][version] = 1.x-beta1
projects[debut_section][subdir] = contrib
projects[debut_section][version] = 1.x-beta1
projects[features][subdir] = contrib
projects[features][version] = 1.x-dev 
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.0-beta1
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0-beta2
projects[token][subdir] = contrib
projects[token][version] = 1.0-beta1
projects[views][subdir] = contrib
projects[views][version] = 3.0-alpha1
