<?php
/**
 * @file
 * Code for the Debut RedHen feature.
 */

include_once('debut_redhen.features.inc');

/**
 * Implements hook_default_redhen_membership_type_alter().
 *
 * If there is a 'member' role, tie it to the 'standard' membership type.
 */
function debut_redhen_default_redhen_membership_type_alter(&$items) {
  if (isset($items['standard']) && ($role = user_role_load_by_name('member')) && !(apps_compatible_feature_is_recreating('debut_member'))) {
    $items['standard']->role_id = $role->rid;
  }
}

/**
 * Implements hook_admin_paths().
 */
function debut_redhen_admin_paths() {
  $paths = array(
    'redhen' => TRUE, 
    'redhen/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove broken address field from the RedHen filter form.
 *
 * @todo: remove once http://drupal.org/node/1929448 is applied.
 */
function debut_redhen_form_redhen_filter_form_alter(&$form, &$form_state) {
  unset($form['filter_fieldset']['filters']['fields']['field_address']);
}
